### ISSUE TITLE
mediainfo returns kb/s instead of Kbps in wazzuf-audio

### ISSUE THREAD

**Issue by craig22** [Booloki/wazzuf-ripper#1]
in wazzuf-audio, mediainfo (0.7.91-1) returns "kb/s" instead of the expected "Kbps" so I replaced the line 
	if [[ $AUDIO_SOURCE_BITRATE_STRING == *Kbps* ]]
with this
	if [[ $AUDIO_SOURCE_BITRATE_STRING == *kb/s* ]]

to fix the problem.

**Comment by Booloki** [comment]
Thanks for the report.
